name:                HDBC-mssql
version:             0.1.0.0
github:              "rkaippully/HDBC-mssql"
license:             BSD3
author:              "Raghu Kaippully"
maintainer:          "rkaippully@gmail.com"
copyright:           "2018 Raghu Kaippully"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            MS SQL Server driver for HDBC
description:         This package provides a cross-platform, pure Haskell MS SQL Server driver for
                     HDBC. This driver does not depend on ODBC.
category:            Database

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - HDBC >= 2.4 && < 2.5

tests:
  HDBC-mssql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HDBC-mssql
